name: eSkyblock
main: eSkyblock\Main
version: 1.1.1
api: 5.0.0
author: Emir
description: Oyuncu bazlı MultiWorld void dünyalarında menülü Skyblock adası oluşturma

commands:
  ada:
    description: Skyblock menüsünü açar
    usage: /ada
    permission: eSkyblock.command.ada

permissions:
  eSkyblock.command.ada:
    description: Ada menüsünü açma izni
    default: true
