name: SkyblockFormIsland
main: Skyblock\Main
version: 3.1.0
api: 5.0.0
author: Emir & Copilot
description: Skyblock ada men端s端 (EasyEdit schematic)
commands:
  ada:
    description: Skyblock ada men端s端
    usage: "/ada"
    permission: skyblock.command.ada
permissions:
  skyblock.command.ada:
    default: true
