name: SkyblockFormIsland
main: Skyblock\Main
version: 1.1.0
api: 5.0.0
author: Emir
description: FormAPI ile Skyblock ada men端s端
commands:
  ada:
    description: Skyblock ada men端s端
    usage: "/ada"
    permission: skyblock.command.ada
permissions:
  skyblock.command.ada:
    default: true
