name: SkyblockFormIsland
main: Skyblock\Main
version: 2.0.0
api: 5.0.0
author: Emir 
description: Skyblock islands cloned from a .mcworld template via FormAPI menu
commands:
  ada:
    description: Skyblock ada menüsü
    usage: "/ada"
    permission: skyblock.command.ada
permissions:
  skyblock.command.ada:
    default: true
