name: SkyblockFormIsland
main: Skyblock\Main
version: 1.2.0
api: 5.0.0
author: Emir & Copilot
description: FormAPI ile Skyblock ada menüsü (güvenli chunk oluşturma)
commands:
  ada:
    description: Skyblock ada menüsü
    usage: "/ada"
    permission: skyblock.command.ada
permissions:
  skyblock.command.ada:
    default: true
