name: Skyblock
main: Skyblock\Main
version: 1.0.0
api: 5.0.0
author: Sen
commands:
  ada:
    description: Ada menüsünü açar
    usage: /ada
    permission: skyblock.command.ada

permissions:
  skyblock.command.ada:
    description: Oyuncuların /ada komutunu kullanabilmesi için izin
    default: true
